### ISSUE TITLE
Test 64bits

### ISSUE THREAD

**Issue by glira** [kost/scexec#1]
please test the 64bit version on an upgraded windows here I did the test and is not working, only work in  the 32bit version.

Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: scexec-win64.exe
  Application Version:  0.0.0.0
  Application Timestamp:    53a7c6cf
  Fault Module Name:    ntdll.dll
  Fault Module Version: 6.1.7600.16385
  Fault Module Timestamp:   4a5be02b
  Exception Code:   c0000005
  Exception Offset: 0000000000018a54
  OS Version:   6.1.7600.2.0.0.256.1
  Locale ID:    1033
  Additional Information 1: a5f8
  Additional Information 2: a5f89aa60f78d49d900b053fd9399670
  Additional Information 3: 2e62
  Additional Information 4: 2e62e11a5a8f76bf573dfeedc730b187

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by kost** [comment]
What Windows version are you using? What payload you use? How did you generate payload? Just trying to reproduce..

**Comment by glira** [comment]
sorry to bother you, my payload was 32bit so not working

**Comment by kost** [comment]
OK. So i guess you learned you should use scexec-win32.exe for 32 bit payloads even on 64 systems and scexec-win64.exe for 64 bit payloads.
